// Japanese log sentences.
//
// `LogCataloguePartial`, so it may omit a key: `logStringsFor` fills the gap
// from `src/logsEn.ts`. `npm run i18n:check` lists what is still missing.
// Keep sentences short, as in the English table. Skill tags stay in English to
// match the Skill Type picker, which `src/uiJa.ts` leaves untranslated.

var LogsJa: LogCataloguePartial = {
  [Log.Run.Start]: '[TsumTsum] 開始',
  [Log.Run.StartBusy]: '[TsumTsum] 前回の実行が停止中のため、開始しません',
  [Log.Run.Stop]: '[TsumTsum] 停止',
  [Log.Run.StopSlow]: '[TsumTsum] タスクループの終了待ち',
  [Log.Task.LoopStopped]: 'TaskController 停止',
  [Log.Task.StoodAside]: 'ラウンド中のため、雑務は後回し',
  [Log.Board.Recognized]: 'ツムを認識',
  [Log.Board.RecognitionStart]: 'ツムの認識を開始',
  [Log.Board.RecognitionTime]: 'ツムの認識完了',
  [Log.Board.PathStart]: 'ルート計算を開始',
  [Log.Board.PathDone]: 'ルートを計算',
  [Log.Board.LinkReach]: 'つなぐ距離',
  [Log.Board.DeadScan]: 'チェーンを引いたがツムが残っている',
  [Log.Board.ChainDrawn]: 'チェーンを引いた。ゲームが反応',
  [Log.Board.Stalled]: '盤面がチェーンを受け付けないため、ファンを使用',
  [Log.Bubble.Cleared]: 'ボムを消去',
  [Log.Bubble.Generated]: 'ボム発生',
  [Log.Skill.Use]: 'スキルを使用',
  [Log.Skill.ReadyAgain]: 'スキルが再び満タン。ボムを割ってから再発動',
  [Log.Skill.StillRunning]: 'スキル発動中のため、タップしない',
  [Log.Skill.TiaraNoDream]: '[Tiara] 吹き出しなし',
  [Log.Skill.TiaraDimDream]: '[Tiara] 読み取る前に吹き出しが消えた',
  [Log.Skill.TiaraBusy]: '[Tiara] 盤面が動いているが発動',
  [Log.Skill.TiaraDream]: '[Tiara] 吹き出しを表示',
  [Log.Skill.TiaraPicked]: '[Tiara] タップ',
  [Log.Skill.TiaraUnsure]: '[Tiara] 確かな一致なし、停止',
  [Log.Skill.FormalBeastModeStart]: '[Formal Beast] ツインゲージ出現。両方を均等にためる',
  [Log.Skill.FormalBeastModeEnd]: '[Formal Beast] ツインゲージ終了',
  [Log.Skill.ElsaDone]: '[Coronation Elsa] 凍結時間終了',
  [Log.Skill.ElsaRoundOver]: '[Coronation Elsa] 凍結時間中にラウンド終了',
  [Log.Skill.ElsaLegacyDone]: '[Coronation Elsa Legacy] 凍結時間終了',
  [Log.Skill.GastonClear]: '[Gaston] 残りのツムを消去',
  [Log.Skill.GastonDone]: '[Gaston] 時間終了',
  [Log.Skill.GastonPass]: '[Gaston] チェーンを引いた',
  [Log.Skill.RapunzelDone]: '[Rapunzel+] 混色チェーンを引いた',
  [Log.Skill.LorcanaAuroraDone]: '[Lorcana Aurora] ボムのチェーンを引いた',
  [Log.Skill.LorcanaAuroraNoChain]: '[Lorcana Aurora] つなぐボムがなく、スキルが無駄に',
  [Log.Skill.LorcanaAuroraStayed]: '[Lorcana Aurora] ボムが残った。チェーンが通らず',
  [Log.Skill.LorcanaAuroraSwept]: '[Lorcana Aurora] ボムをその場で割った',
  [Log.Play.GameStart]: 'ゲーム開始',
  [Log.Play.GamingFast]: 'プレイ中',
  [Log.Play.GameOver]: 'ゲーム終了',
  [Log.Play.ConfirmingGameOver]: '不明な画面。ゲーム終了か確認中',
  [Log.Play.CheckBonusItems]: 'アイテムを確認',
  [Log.Play.RoundDelayStarted]: '次のラウンドまで待機',
  [Log.Play.RoundDelayOver]: '待機終了。次のラウンドへ',
  [Log.Play.RoundDelaySkipped]: '待機を打ち切り。次のラウンドへ',
  [Log.Play.RoundTimeUp]: 'ラウンドの最大時間に到達',
  [Log.Play.RoundCoasting]: 'ラウンドの終了待ち',
  [Log.Tsums.Detected]: '設定ページからマイツムを取得',
  [Log.Tsums.Identified]: 'マイツムを判定',
  [Log.Tsums.Unidentified]: '選択中のツムが不明。ツムなしで記録',
  [Log.Tsums.Unreadable]: 'プレイ開始前のツムアイコンを読み取れない',
  [Log.Tsums.NoLibrary]: 'ツムのライブラリがない。ツムなしで記録',
  [Log.Tsums.StaleTemplate]: 'ツムのライブラリがこのリリースと不一致のため無視',
  [Log.Tsums.NoBoardColors]: 'ライブラリに盤面の色がないため、スキルボタンから取得',
  [Log.Lorcana.Transformed]: '[Lorcana] 変身した',
  [Log.Lorcana.Untransformed]: '[Lorcana] ゲージの輪が戻った。変身していない',
  [Log.Fever.Start]: '[Fever] フィーバータイム',
  [Log.Fever.End]: '[Fever] フィーバー終了',
  [Log.Screen.Detect]: '画面を検出中',
  [Log.Screen.CalculateSize]: '画面サイズを計算中',
  [Log.Screen.Offset]: '画面のオフセットとサイズ',
  [Log.App.Start]: 'ツムツムを起動',
  [Log.Page.Current]: '現在の画面',
  [Log.Page.Friends]: '友だち画面',
  [Log.Page.Tsums]: 'ツム一覧画面',
  [Log.Gifts.ReceiveAll]: 'ギフトを一括受け取り',
  [Log.Gifts.ReceiveOneByOne]: 'ギフトを1通ずつ受け取り',
  [Log.Gifts.ReceiveAgain]: 'ギフトを再度受け取り',
  [Log.Gifts.AllReceived]: 'すべてのギフトを受け取った',
  [Log.Gifts.Completed]: 'ギフトの受け取り完了',
  [Log.Gifts.CheckUnreceived]: '未受け取りのギフトを確認',
  [Log.Gifts.ReceiveOneSkippedOnly]: 'メールボックスにはスキップしたメールのみ',
  [Log.Hearts.ReadRecords]: '記録を読み込み中',
  [Log.Hearts.SaveRecords]: '記録を保存中',
  [Log.Hearts.SendStart]: 'ハート送信を開始',
  [Log.Hearts.SendDone]: 'ハート送信完了',
  [Log.Hearts.Screenful]: 'この画面のハートを送信',
  [Log.Hearts.ListEnd]: 'ランキングの最後に到達',
  [Log.Hearts.ZeroScore]: 'スコアのない友だちに到達',
  [Log.Hearts.TimeUp]: '時間切れ',
  [Log.Report.Saved]: '報告を保存',
  [Log.Report.Failed]: '報告を保存できず',
  [Log.Walk.Start]: '操作を記録中: 自分でゲームを操作してください',
  [Log.Walk.Page]: '画面を記録',
  [Log.Walk.Tap]: 'タップを記録',
  [Log.Walk.Done]: '操作の記録完了',
  [Log.Unlock.NowQueued]: '次のループでレベル上限を解放',
  [Log.Unlock.NowRefused]: '今はレベル上限を解放しない',
  [Log.Unlock.NowWaiting]: 'ラウンド中のため、終了後にレベル上限を解放',
  [Log.Unlock.NowYielded]: 'レベル上限の解放を優先',
  [Log.Unlock.Start]: '上限に達したツムを探索中',
  [Log.Unlock.Raised]: 'ツムのレベル上限を解放',
  [Log.Unlock.NextPage]: 'この画面に上限のツムなし。次のページへ',
  [Log.Unlock.SortFailed]: 'ツム一覧を並べ替えられない',
  [Log.Unlock.SortRestored]: 'ツム一覧の並び順を復元',
  [Log.Unlock.RaiseNotConfirmed]: 'レベル上限が解放されない。コイン不足？',
  [Log.Unlock.Retrying]: '解放に失敗。ツム一覧を開き直し',
  [Log.Unlock.End]: 'レベル上限の解放完了',
  [Log.Unlock.MyTsumCapped]: 'マイツムがレベル上限',
  [Log.Unlock.MyTsumStart]: 'マイツムのレベル上限を解放中',
  [Log.Unlock.MyTsumNotSelected]: 'ツム一覧にマイツムが表示されていないため、解放しない',
  [Log.Unlock.MyTsumBackoff]: 'マイツムの解放に失敗。後で再試行',
  [Log.Unlock.MyTsumEnd]: 'マイツムのレベル上限の解放完了',
  [Log.Box.NowQueued]: '次のループでBOXを購入',
  [Log.Box.NowRefused]: '今はBOXを購入しない',
  [Log.Box.NowWaiting]: 'ラウンド中のため、終了後にBOXを購入',
  [Log.Box.Start]: 'ショップへBOXを購入しに行く',
  [Log.Box.StoreLoading]: 'ショップのBOXが読み込まれない',
  [Log.Box.NotOffered]: '本日はこのBOXの販売なし',
  [Log.Box.TabNotTaken]: 'ショップでこのBOXを開けない',
  [Log.Box.Buying]: 'BOXを購入中',
  [Log.Box.Bought]: 'BOXを購入',
  [Log.Box.SoldOut]: 'BOX売り切れ',
  [Log.Box.NoCoins]: 'コイン不足のためキャンセル。ルビーは未使用',
  [Log.Box.TenRefused]: 'ショップが10連を拒否。BOXはほぼ売り切れ',
  [Log.Box.ToastStuck]: '10連拒否の表示が閉じない',
  [Log.Box.DialogMissing]: '購入確認が表示されない',
  [Log.Box.Retrying]: '購入に失敗。ショップ画面を開き直し',
  [Log.Box.RevealsStuck]: 'BOXの開封演出が止まった',
  [Log.Box.PurchaseLimit]: '購入上限に到達',
  [Log.Box.End]: 'BOX購入完了'
}

logRegisterStrings(Locale.Japanese, LogsJa);
